[package]
name = "fisher"
version = "1.0.0-beta.2"
license = "GPL-3.0"

description = "Webhooks catcher written in Rust"
authors = ["Pietro Albini <pietro@pietroalbini.io>"]
readme = "README.md"

repository = "https://github.com/pietroalbini/fisher"

build = "build.rs"

[dependencies]
url="^1.2"
ansi_term="^0.9"
regex="^0.1"
clap="^2.11"
chan="^0.1"
chan-signal="^0.1"
rustc-serialize="^0.3"
lazy_static="^0.2"
rand="^0.3"
tiny_http="^0.5"

# Dependencies for the "provider-github" feature
ring = { version=">=0.4, <=0.5", optional=true }

[dev-dependencies]
hyper="^0.9"

[build-dependencies]
rustc_version="^0.1"

[features]
default = ["provider-github", "provider-gitlab"]

provider-github = ["ring"]
provider-gitlab = []

[profile.release]
lto = true
